export const LOAD_POKEMON_REQUEST = "LOAD_POKEMON_REQUEST";
export const LOAD_POKEMON_SUCCESS = "LOAD_POKEMON_SUCCESS";
export const LOAD_POKEMON_FAILED = "LOAD_POKEMON_FAILED";

export const LOAD_DETAIL_POKEMON_REQUEST = "LOAD_DETAIL_POKEMON_REQUEST";
export const LOAD_DETAIL_POKEMON_SUCCESS = "LOAD_DETAIL_POKEMON_SUCCESS";

export const LOAD_FILTER_POKEMON_REQUEST = "LOAD_FILTER_POKEMON_REQUEST";
export const LOAD_FILTER_POKEMON_SUCCESS = "LOAD_FILTER_POKEMON_SUCCESS";
